### ISSUE TITLE
Don't hang in `createHistoryStream()` when blocks are not available

### ISSUE THREAD

**Issue by josephmturner** [holepunchto/hyperbee#167]
`createHistoryStream` currently hangs when blocks are not available.  I would like to iterate over the full history of a hyperbee which is not fully replicated.  Could `createHistoryStream()` accept a `{ wait: false }` argument to make it keeping loop when it encounters `BLOCK_NOT_AVAILABLE`?  Perhaps this API could be used like this:

```
for await (const entry of db.createHistoryStream({ wait: false })) {
  if (entry.type = 'put') handlePut()
  if (entry.type = 'del') handleDel()
  if (entry.type = 'BLOCK_NOT_AVAILABLE') handleMissingBlock()
}
```

**Comment by josephmturner** [comment]
Hi @mafintosh!  Would you please share your thoughts on this feature request?

I am working on an hyperdrive-based app which includes a UI for exploring the history of a specific file:

![2024-11-14-210849_473x131_scrot](https://github.com/user-attachments/assets/eaff7824-28ac-4997-ac2b-6ff2f106ab03)
I show off this feature starting at 32:30 in [this video demonstration](https://emacsconf.org/2023/talks/hyperdrive/).

We more or less do this:

```javascript
const history = []
for await (const entry of snapshot.db.sub('files').createHistoryStream({ reverse: true })) {
  if (entry.key === key) history.push(entry)
}
```

However the history stream hangs if you're offline and haven't already fully replicated the metadata hyperbee.  I'd like to use `wait: false`:

```javascript
const history = []
for await (const entry of snapshot.db.sub('files').createHistoryStream({ reverse: true, wait: false })) {
  if (entry.type === 'BLOCK_NOT_AVAILABLE' &&
    history[history.length - 1]?.type === 'BLOCK_NOT_AVAILABLE') {
    // If the prior history entry was not available, modify it
    // so there's only one BLOCK_NOT_AVAILABLE entry in a row.
    history[history.length - 1].seq = entry.seq
  } else {
    if (entry.key === key) history.push(entry)
  }
}
```

Do you think an API like in [PR #168](https://github.com/holepunchto/hyperbee/pull/168) makes sense?

Thank you for your help!

Joseph

**Comment by josephmturner** [comment]
Ping @HDegroote @mafintosh

**Comment by mafintosh** [comment]
Hi! Sorry missed your issue / PR. Happy to add an option wait, but it should then throw like the rest of the apis if the block is missing. If you wanna do anything more advanced than that you can easily iterate the core yourself and decode ondemand

**Comment by josephmturner** [comment]
> Happy to add an option wait, but it should then throw like the rest of the apis if the block is missing. If you wanna do anything more advanced than that you can easily iterate the core yourself and decode ondemand

I agree that throwing would be more consistent.  However, IIUC this means that we can't handle `BLOCK_NOT_AVAILABLE` errors from within the `createHistoryStream` iterator.  The `try..catch` block would have to wrap the call to `createHistoryStream` and then if you want to continue iterating where you left off in case of missing blocks, you have to call `createHistoryStream` again, which is slow.

How would you recommend that I quickly load the sparse history for a particular file?

Thank you!

Joseph

**Comment by josephmturner** [comment]
@mafintosh I am wrapping `createHistoryStream` in `try..catch` and the performance is good enough.  Thank you for your help!!

In case anyone is curious, here's how I'm getting the sparse history for a single file:

https://git.sr.ht/~ushin/hypercore-fetch-ushin/tree/e2d7e718881e280c5198a377e69e63b0e70afdf9/item/index.js#L1331

Joseph
