### ISSUE TITLE
issue with hyperbee.put

### ISSUE THREAD

**Issue by shikhars371** [holepunchto/hyperbee#71]
hello , below code give me the error as no update available from peers

  const { corestore, replicate } = new Client()
  const store = corestore()

  // Get the stats core.
  const statsCore = store.get({ key: STATS_CORE_KEY, valueEncoding: 'json' })

  const db = new Hyperbee(statsCore, { keyEncoding: 'utf-8', valueEncoding: 'utf-8' })

  await db.ready()

  await db.put('a', 'b')
await db.put('c', 'd')

**Comment by mafintosh** [comment]
Use the latest stack, the daemon is deprecated.
